# Generated by Django 3.1.7 on 2021-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(upload_to='images/')),
                ('destination_name', models.CharField(max_length=50)),
                ('destination_description', models.CharField(max_length=200)),
                ('package_price', models.IntegerField()),
            ],
        ),
    ]
