# Generated by Django 3.1.7 on 2021-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_heading', models.CharField(max_length=100)),
                ('blog_desc', models.CharField(max_length=200)),
                ('blog_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(upload_to='images/')),
                ('destination_name', models.CharField(max_length=50)),
                ('destination_description', models.CharField(max_length=200)),
                ('package_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('sourceLocation', models.CharField(max_length=30)),
                ('destinationLocation', models.CharField(max_length=30)),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('fareEconomy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fareBusiness', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fareFirst', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numSeatsRemainingEconomy', models.IntegerField()),
                ('numSeatsRemainingBusiness', models.IntegerField()),
                ('numSeatsRemainingFirst', models.IntegerField()),
            ],
        ),
    ]
