# Generated by Django 3.1.7 on 2021-03-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_heading', models.CharField(max_length=100)),
                ('blog_desc', models.CharField(max_length=200)),
                ('blog_date', models.DateTimeField()),
            ],
        ),
    ]
