# Generated by Django 3.1.7 on 2021-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('sourceLocation', models.CharField(max_length=30)),
                ('destinationLocation', models.CharField(max_length=30)),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField()),
                ('fareEconomy', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fareBusiness', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fareFirst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numSeatsRemainingEconomy', models.IntegerField()),
                ('numSeatsRemainingBusiness', models.IntegerField()),
                ('numSeatsRemainingFirst', models.IntegerField()),
            ],
        ),
    ]
