# Generated by Django 3.1.7 on 2021-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(default='hotel', max_length=50)),
                ('hotel_type', models.IntegerField()),
                ('hotel_image', models.ImageField(upload_to='images/')),
                ('dailyCost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
