# Generated by Django 3.1.7 on 2021-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_blog_user_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
