# Generated by Django 3.1.7 on 2021-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210518_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='blog_date',
            field=models.DateField(),
        ),
    ]
