# Generated by Django 3.1.7 on 2021-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210518_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
